package com.example.demo.service;

import com.example.demo.model.WaybillRecord;
import com.example.demo.repository.WaybillFileRepository;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

@Service
public class BluedartWaybillService {

    private final BluedartAuthService authService;
    private final WaybillFileRepository repository;
    private final RestTemplate restTemplate = new RestTemplate();

    public BluedartWaybillService(
            BluedartAuthService authService,
            WaybillFileRepository repository
    ) {
        this.authService = authService;
        this.repository = repository;
    }

    @SuppressWarnings("unchecked")
    public Map<String, Object> generateWaybill(Map<String, Object> requestBody) {

        String jwtToken = authService.getJwtToken();

        HttpHeaders headers = new HttpHeaders();
        headers.set("JWTToken", jwtToken);
        headers.setContentType(MediaType.APPLICATION_JSON);

        HttpEntity<Map<String, Object>> entity =
                new HttpEntity<>(requestBody, headers);

        ResponseEntity<Map> response = restTemplate.postForEntity(
                "https://apigateway-sandbox.bluedart.com/in/transportation/waybill/v1/GenerateWayBill",
                entity,
                Map.class
        );

        Map<String, Object> responseBody = response.getBody();
        if (responseBody == null) {
            throw new RuntimeException("Empty response from Bluedart");
        }

        Map<String, Object> result =
                (Map<String, Object>) responseBody.get("GenerateWayBillResult");

        if (result == null || result.get("AWBNo") == null) {
            throw new RuntimeException("Waybill not generated by Bluedart");
        }

        String awbNo = result.get("AWBNo").toString();

        // ✅ SAFE save
        try {
        repository.save(
                new WaybillRecord(
                        awbNo,
                        extractCreditRef(requestBody),
                        requestBody,
                        responseBody
                )
        );

        } catch (Exception e) {
            // Log the error (omitted for brevity)
            System.err.println("Failed to save WaybillRecord: " + e.getMessage());
        }

        return responseBody;
    }

    private String extractCreditRef(Map<String, Object> requestBody) {
        try {
            Map<String, Object> req =
                    (Map<String, Object>) requestBody.get("Request");
            Map<String, Object> services =
                    (Map<String, Object>) req.get("Services");
            return services.getOrDefault("CreditReferenceNo", "NA").toString();
        } catch (Exception e) {
            return "NA";
        }
    }
}
