package com.example.demo.service;

import com.example.demo.model.WaybillRecord;
import com.example.demo.repository.WaybillFileRepository;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;

@Service
public class BluedartWaybillService {

    private final BluedartAuthService authService;
    private final WaybillFileRepository repository;
    private final RestTemplate restTemplate = new RestTemplate();

    public BluedartWaybillService(
            BluedartAuthService authService,
            WaybillFileRepository repository
    ) {
        this.authService = authService;
        this.repository = repository;
    }

    @SuppressWarnings("unchecked")
public Map<String, Object> generateWaybill(Map<String, Object> requestBody) {

    String jwtToken = authService.getJwtToken();

    HttpHeaders headers = new HttpHeaders();
    headers.set("JWTToken", jwtToken);
    headers.setContentType(MediaType.APPLICATION_JSON);

    HttpEntity<Map<String, Object>> entity =
            new HttpEntity<>(requestBody, headers);

    Map<String, Object> responseBody;

    try {
        System.out.println("➡️ Sending request to Bluedart:");
        System.out.println(requestBody);

        ResponseEntity<Map> response = restTemplate.postForEntity(
                "https://apigateway-sandbox.bluedart.com/in/transportation/waybill/v1/GenerateWayBill",
                entity,
                Map.class
        );

        responseBody = response.getBody();

        if (responseBody == null) {
            throw new RuntimeException("Empty response from Bluedart");
        }

    } catch (Exception e) {
        System.err.println("❌ Bluedart API FAILED");
        System.err.println("➡️ Payload that caused failure:");
        System.err.println(requestBody);
        e.printStackTrace();
        throw new RuntimeException("Bluedart API error", e);
    }

    /* ---------- VALIDATE RESPONSE ---------- */

    Map<String, Object> result =
            (Map<String, Object>) responseBody.get("GenerateWayBillResult");

    if (result == null || result.get("AWBNo") == null) {
        throw new RuntimeException(
                "Waybill not generated by Bluedart. Response: " + responseBody
        );
    }

    String awbNo = result.get("AWBNo").toString();

    /* ---------- PERSIST WAYBILL ---------- */

    try {
        repository.save(
                new WaybillRecord(
                        awbNo,
                        extractCreditRef(requestBody),
                        requestBody,
                        responseBody
                )
        );
    } catch (Exception e) {
        // Persistence failure should NOT hide Bluedart success
        System.err.println("⚠️ Failed to save WaybillRecord for AWB: " + awbNo);
        e.printStackTrace();
    }

    return responseBody;
}


    private String extractCreditRef(Map<String, Object> requestBody) {
        try {
            Map<String, Object> req =
                    (Map<String, Object>) requestBody.get("Request");
            Map<String, Object> services =
                    (Map<String, Object>) req.get("Services");
            return services.getOrDefault("CreditReferenceNo", "NA").toString();
        } catch (Exception e) {
            return "NA";
        }
    }

    public List<WaybillRecord> generateBulkWaybills(List<Map<String,Object>> requests) {

        List<WaybillRecord> records=new ArrayList<>();

        for(Map<String,Object> request:requests){

            Map<String,Object> response = generateWaybill(request);

Map<String,Object> result =
    (Map<String,Object>) response.get("GenerateWayBillResult");

String awbNo = result.get("AWBNo").toString();

WaybillRecord record = repository.findByAwbNo(awbNo);


            if(record!=null) {
            records.add(record);
            }
        }
        repository.saveAll(records);
        
        return records;
    }
}
